# Generated by Django 2.0.4 on 2018-07-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(help_text='Ej: 962458090', max_length=9)),
                ('direccion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='profesor')),
            ],
        ),
    ]
